version: 1

packageName: ALOL

capabilities:
  - inventory
  - storage
  - http
  - event-bus
  - receipts

#daemons:
#  - name: suggestion
#    events:
#      - evo.receipt.opened
#      - evo.receipt.productAdded
#      - evo.receipt.productRemoved
#      - evo.receipt.closed
#      - app.suggestion.used
#    behavior: suggestion-daemon.js

#plugins:
#  - name: suggestion
#    moment: evo.receipt.items.fixed
#    point: before
#    behavior: before-receipt-fixed.js

views:
  - name: discount-request
    source: discount-request.html
    scripts: # script list to be included
      - discount-request.js
    styles: # style list to be included
      - "*.css" # может подключить все файлы
