version: 1

packageName: ALOL

capabilities:
  - http
  - receipts
#  - inventory
#  - storage
#  - event-bus

#daemons:
#  - name: suggestion
#    events:
#      - evo.receipt.opened
#      - evo.receipt.productAdded
#      - evo.receipt.productRemoved
#      - evo.receipt.closed
#      - app.suggestion.used
#    behavior: suggestion-daemon.js

#plugins:
#  - name: suggestion
#    moment: evo.receipt.items.fixed
#    point: before
#    behavior: before-receipt-fixed.js

plugins:
  - name: alol
    moment: evo.receipt.items.fixed
    point: before
    behavior: before-receipt-fixed.js

views:
  - name: discount-request
    header: "АЛОЛЬ"
    source: client/views/alol/discount-request.html
    scripts:
      - discount-request.js
    styles:
      - "*.css"

#  - name: suggestion-list
#    header: "Предложите клиенту"
#    source: client/views/suggestion-list/view.html
#    scripts: # список скриптов которые должны быть подключены
#      - suggestion-list-view.js
#    styles: # список стилей которые должны быть подключены
#      - "*.css" # может подключить все файлы

#  - name: launcher
#    header: "Mint Whale"
#    source: client/views/mint-whale-blank/mint-whale-blank.html
#    scripts:
#      - no-script
#    styles:
#      - "*.css"