version: 1

packageName: mintWhale

capabilities:
  - inventory
  - storage
  - http
  - event-bus
  - receipts

daemons:
  - name: suggestion
    events:
      - evo.receipt.opened
      - evo.receipt.productAdded
      - evo.receipt.productRemoved
      - evo.receipt.closed
      - app.suggestion.used
    behavior: suggestion-daemon.js

plugins:
  - name: suggestion
    moment: evo.receipt.items.fixed
    point: before
    behavior: before-receipt-fixed.js

views:
  - name: suggestion-list
    source: view.html
    scripts: # список скриптов которые должны быть подключены
      - suggestion-list-view.js
    styles: # список стилей которые должны быть подключены
      - "*.css" # может подключить все файлы
